version: '3.5'

services:
  menumaster:
    build:
      context: '.'
    container_name: menumaster-app
    ports:
      - 80:80
    volumes:
      - .:/var/www/html/
    depends_on:
      - "menumaster-db"
      - "menumaster-mail"
      - "menumaster-nodejs" 
    networks:
      - app

  menumaster-db:
    image: mysql:8
    tty: true
    container_name: menumaster-db
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - DB_CONNECTION=mysql
      - DB_HOST=menumaster-db
      - DB_PORT=3306
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      - app

  menumaster-mail:
    image: mailhog/mailhog:latest
    container_name: menumaster-mail
    ports:
      - "8125:8025"
      - "2525:1025"
    environment:
      - MT_USER=dashfluit
      - MT_PASSWD=dashfluit
      - MT_MAILBOX_LIMIT=512000001
      - MT_MESSAGE_LIMIT=102400001'
    networks:
      - app
    
  menumaster-redis:
    image: redis:latest
    container_name: menumaster-redis
    ports:
      - 6379:6379
    networks:
      - app

  #Para o node dar certo precisar rodar o comando npm install localmente anstes de iniciar o docker

  menumaster-nodejs:  # Adicionando o serviço Node.js
    image: node:latest  # Use a versão do Node.js desejada
    container_name: menumaster-nodejs
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html/
    command: ["npm", "run", "dev"]  # Substitua pelo seu comando Vite
    ports:
     - 3009:3009
    depends_on:
      - "menumaster-db"
    networks:
      - app
networks:
  app:
    driver: bridge
